# Generated by Django 3.1.1 on 2020-09-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyticket_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieshow',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
