# Generated by Django 3.1.1 on 2020-09-05 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyticket_app', '0004_booking_booking_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_uuid',
            field=models.UUIDField(default=uuid.UUID('b65f8b2e-9ec6-41eb-a92e-cc8c43e0680c'), unique=True),
        ),
    ]
